package com.zone24x7.wifi_settings;

public enum EC {

    SSID_IS_NULL_OR_EMPTY,

    PERMISSIONS_NOT_GRANTED,
    WIFI_DISABLED,
    LOCATION_DISABLED,

    RECONNECTION_FAILED,
    FAILED_TO_ENABLE_NETWORK,
    WIFI_MANAGER_ERROR,
    NETWORK_NOT_VISIBLE
    
}
